### ISSUE TITLE
Write `mopro build` targets in `Config.toml`

### ISSUE THREAD

**Issue by vivianjeng** [zkmopro/mopro#294]
# Justification
Improving DX by removing need to create manual config

# Problem
We have completed #264 for creating a config file for `mopro create`
but when users run `mopro build` more than once, they have to select targets multiple times
There are
- Build mode
- Select platform(s) (already in config file)
- iOS architecture(s) / Android architecture(s)

We can save also **build mode** and **architecture(s)** in config file to easily build again

## Details
Like #282,
save the build mode and architectures in the `Config.toml`
e.g.
```toml
target_adapters = []
target_platforms = []
build_mode = [] # build or release
ios_architectures = [] # 3 iOS architectures list
android_architectures = [] # 4 Android architectures list
```
and enable the checkbox if it is in config file
disable the checkbox if it is not in the config file

## Acceptance criteria
- save `build_mode`, `ios_architectures`, `android_architectures` in `Cargo.toml`
- and run `mopro build` again to enable the checkboxes if it is saved in `Cargo.toml`
