### ISSUE TITLE
re-export uniffi

### ISSUE THREAD

**Issue by vivianjeng** [zkmopro/mopro#356]
# Problem
Now the test e2e needs to import both `mopro-ffi` and `uniffi` to make it generate bindings

## Details
We can simplify this by re-exporting `uniffi` in `mopro-ffi`
so the users can just use

```toml
[dependencies]
mopro-ffi = "0.1"

[build-dependencies]
mopro-ffi = "0.1"
```

instead of
```toml
[dependencies]
mopro-ffi = "0.1"
uniffi = "0.29"

[build-dependencies]
mopro-ffi = "0.1"
uniffi = { version = "0.29", features = ["build"]}
```

We can also make it optional
e.g.
user can choose to use the 2nd way if he wants to use specific version of uniffi
and use a feature flag `uniffi` to export the default `uniffi` version
or it becomes
```toml
[dependencies]
mopro-ffi = {version = "0.1", features = ["uniffi"]}

[build-dependencies]
mopro-ffi = {version = "0.1", features = ["uniffi"]}
```

## Acceptance criteria
If the user removes `uniffi` dependencies, `mopro-ffi` can still generate bindings
